name: deploy-frontend

on:
  push:
    tags:
      - 'v*'

jobs:
  frontend-management:
    runs-on: ubuntu-latest
    steps:
      - name: Docker - Fetch metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: nicerwang/avp_frontend
      - uses: actions/checkout@v2
      - name: Node.js - Set up
        uses: actions/setup-node@v2.4.1
      - name: NPM - Build
        run: npm install && npm run build
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Docker - Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker - Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: Deploy bash
        uses: fifsky/ssh-action@master
        with:
          command: |
            sh update.sh
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}